### ISSUE TITLE
#-comments not recognized

### ISSUE THREAD

**Issue by triplem** [paradigmatic/Configrity#9]
During the test of an application, we had some comments in the configuration loaded via loadresource, like

<pre>
# key =
</pre>

The configuration is always complaining about the wrong assigment: 

<pre>
org.streum.configrity.io.StandardFormat$ParserException: [7.3] failure: `=' expected but `k' found
</pre>

**Comment by Rogach** [comment]
I saw this one - if you add that "=" after "#", it starts complaining about missing "[".

Thus things start to work only when you have "#=[]" at the end of the file.

**Comment by paradigmatic** [comment]
Thanks for reporting the bugs. Unfortunately, I was unable to reproduce them. I wrote to new tests with your examples and everything is green (see the changeset SHA: 34c588d3ae16dc3634425a2f1190350d9f07ff92). 

Can you please post a minimal configuration file which displays the errors ? I will try to correct them as soon as possible.

**Comment by triplem** [comment]
<pre>
# key =
</pre>

produces: 

<pre>
 org.streum.configrity.io.StandardFormat$ParserException: [4.3] failure: `=' expected but `k' found
</pre>


<pre>
#key =
</pre> 

produces: 

<pre>
org.streum.configrity.io.StandardFormat$ParserException: [4.7] failure: `[' expected but end of source found
</pre>

I am working with version:
"org.streum" %% "configrity-core" % "0.10.0"

**Comment by paradigmatic** [comment]
As stated in the [wiki](https://github.com/paradigmatic/Configrity/wiki/Formats), the values which contain whitespaces must be quoted. In the test case you submitted, the problem arises because the value of `baz = hello world` must be quoted. If you replace it by `baz = "hello world"`, it works as expected.

I think the error message is not clear enough, but currently I don't know how to make it more helpful. Any advice/contribution are welcome.
